// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6z_jJ7_B5PSnSqul7VuinBcPZUsL8hjs',
    appId: '1:311839308759:web:c4fd61ac0c95836ddce992',
    messagingSenderId: '311839308759',
    projectId: 'new-app-147d7',
    authDomain: 'new-app-147d7.firebaseapp.com',
    storageBucket: 'new-app-147d7.firebasestorage.app',
    measurementId: 'G-JG6G3JKXRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXQgoKLTV6enqXrIL9Fi5kagv3OObYEKk',
    appId: '1:311839308759:android:acb95e3da467edebdce992',
    messagingSenderId: '311839308759',
    projectId: 'new-app-147d7',
    storageBucket: 'new-app-147d7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCim9KO7oakmzZXZjBZk7u95-UmzpWgeXw',
    appId: '1:311839308759:ios:0937b92bcaadb9ffdce992',
    messagingSenderId: '311839308759',
    projectId: 'new-app-147d7',
    storageBucket: 'new-app-147d7.firebasestorage.app',
    iosBundleId: 'com.example.worldnews',
  );
}
